version: '3.9'

services:
  traefik:
    hostname: traefik.devbox
    image: traefik:latest
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    networks:
      - webgateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    command:
      - --accesslog=true
      - --log.level=INFO
      - --api=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=w3i_ssl
      - --certificatesresolvers.w3i_ssl.acme.email=contact@web3invest.fr
      - --certificatesresolvers.w3i_ssl.acme.tlschallenge=true
      - --certificatesresolvers.w3i_ssl.acme.storage=/letsencrypt/acme.json
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --metrics.prometheus=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addrouterslabels=true
      - --metrics.prometheus.addServicesLabels=true

    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.entrypoints=web,websecure
      - traefik.http.routers.traefik.tls.certresolver=w3i_ssl
      - traefik.http.routers.traefik.rule=Host(`network.testnet.web3invest.fr`)

networks:
  webgateway:
    driver: bridge

volumes:
  letsencrypt:
